<?php /** @var \Eleanorsoft\MageplazaBlog\Block\Design $block */ ?>
<?php $color = $block->getHelper()->getBlogConfig('general/font_color'); ?>
<style type="text/css">
    #mpblog-list-container a{
        text-decoration: none;
    }

    /*Post List Content Css*/
    .post-info-wraper h2.mp-post-title a,
    .about-admin h4.admin-title a,
    .mp-post-meta-info a.mp-read-more,
    .mp-post-info a.mp-info,
    ul.menu-categories a.list-categories:hover,
    .products-same-post a.product-item-link:hover,
    a.mp-relate-link,
    .mpblog-product-name{
        color: <?php echo $color ?> !important;
    }

    a.label.label-default.tags-list:hover,
    a.label.label-default.tags-list:focus {
        background: <?php echo $color ?>;
        color: #fff !important;
    }

    .list-post-tabs a{
        background: #fbfbfb;
        color: <?php echo $color ?>;
    }

    /*Site Map CSS*/
    .mp-sidebar a.sitemap-link,
    .menu-archives a.list-archives:hover {
        text-decoration: none !important;
        color: <?php echo $color ?> !important;
    }

    /*Comment CSS*/
    button.default-cmt__content__cmt-block__cmt-box__cmt-btn__btn-submit {
        background: <?php echo $color ?> !important;
        color: #fff;
        border-color: #999 !important;
    }

    button.default-cmt__cmt-login__btn-login {
        background: <?php echo $color ?> !important;
        border-color: #999 !important;
    }

    span.cmt-row__cmt-username {
        font-weight: 600;
        color: <?php echo $color ?>;
    }

    a.interactions__btn-actions {
        color: <?php echo $color ?> !important;
    }

    /*Widget CSS*/
    .widget-title a {
        color: <?php echo $color ?>;
        font-size: 26px;
    }

    /*Author CSS*/
    .author-name h3 {
        color: <?php echo $color ?>;
        text-align: center;
    }
</style>