<?php
/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>

<div class="container account-dasboard">
    <div class="hello-client">
        <?= sprintf(__('hello, %s'), $block->escapeHtml($block->getName())); ?>
    </div>
    <div class="update-your-acc" >
        <?= __('View a snapshot of your recent account activity and update your account information through your Dashboard.'); ?>
    </div>
    <div class="row justify-content-between dashboard">
        <div class="col-4 elements">
            <div class="diamond account-info-element">
                <a href="<?= $block->getUrl('addressbook/address'); ?>" ></a>
                <div class="text-element">
                    <?= __('ACCOUNT<br>INFO'); ?>
                </div>
                <div class="image-logo">
                    <img src="<?= $block->getViewFileUrl('images/account-info-logo.png'); ?>" class="no-act-block" alt="">
                </div>
                <div class="image-logo-2">
                    <img src="<?= $block->getViewFileUrl('images/logo-first-block.png'); ?>" class="act-block" alt="">
                </div>
            </div>
        </div>
        <div class="col-4 elements">
            <div class="diamond order-history-element">
                <a href="<?= $block->getUrl('sales/order/history'); ?>" ></a>
                <div class="text-element">
                    <?= __('ORDER<br>HISTORY'); ?>
                </div>
                <div class="image-logo">
                    <img src="<?= $block->getViewFileUrl('images/order-history-non-active.png'); ?>" class="no-act-block" alt="">
                </div>
                <div class="image-logo-2">
                    <img src="<?= $block->getViewFileUrl('images/order-history-logo.png'); ?>" class="act-block" alt="">
                </div>
            </div>
        </div>
        <div class="col-4 elements">
            <div class="diamond my-wishlist-element">
                <a href="<?= $block->getUrl('wishlist'); ?>" ></a>
                <div class="text-element">
                    <?= __('MY<br>WISHLIST'); ?>
                </div>
                <div class="image-logo">
                    <img src="<?= $block->getViewFileUrl('images/my-whishlist-logo.png'); ?>" class="no-act-block" alt="">
                </div>
                <div class="image-logo-2">
                    <img src="<?= $block->getViewFileUrl('images/logo-third-block.png'); ?>" class="act-block" alt="">
                </div>
            </div>
        </div>
    </div>
</div>