<?php /** @var \Eleanorsoft\ProductBlock\Block\ProductList $block */ ?>
<?php $productCollection = $block->getProductCollection(); ?>
<?php if ($productCollection && $productCollection->getSize()) : ?>
    <?php $iterator = $productCollection->getIterator(); ?>
    <?php /** @var \Magento\Catalog\Model\Product $product */ ?>
    <?php for ($i = 0; $i < $iterator->count();) : ?>
        <?php
        $product1 = $product2 = null;
        try {
            $iterator->seek($i++);
            $product1 = $iterator->current();
            $iterator->seek($i++);
            $product2 = $iterator->current();
        } catch (\Exception $ex) {
        }
        ?>
        <div class="col-md-2 col-sm-4 col-xs-4 sect3-inner-2">
            <?php if ($product1) { ?>
                <div class="sect3-description  sect-3-hide" style="display: none;">
                    <a href="<?= $block->escapeHtml($block->getProductUrl($product1)); ?>">
                        <?php echo $block->escapeHtml($product1->getName()); ?>
                    </a>
                </div>
            <?php } ?>
            <?php if ($product2) { ?>
                <div class="sect3-description  sect-3-2-hide" style="display: none;">
                    <a href="<?= $block->escapeHtml($block->getProductUrl($product2)); ?>">
                        <?php echo $block->escapeHtml($product2->getName()); ?>
                    </a>
                </div>
            <?php } ?>

            <?php if ($product1) { ?>
                <a href="<?= $block->escapeHtml($block->getProductUrl($product1)); ?>">
                    <div class="opacite-block-home-3" style="display: none;"></div>
                    <img
                        class="sect-3-cursor"
                        src="<?php echo $block->getImage($product1, 'category_page_grid')->getImageUrl(); ?>"
                        alt="<?php echo $block->escapeHtml($product1->getName()); ?>"
                    >
                </a>
            <?php } ?>

            <?php if ($product2) { ?>
                <a href="<?= $block->escapeHtml($block->getProductUrl($product2)); ?>">
                    <div class="opacite-block-home-4" style="display: none;"></div>
                    <img
                        class="sect-3-2-cursor"
                        src="<?php echo $block->getImage($product2, 'category_page_grid')->getImageUrl(); ?>"
                        alt="<?php echo $block->escapeHtml($product2->getName()); ?>"
                    >
                </a>
            <?php } ?>
        </div>
    <?php endfor; ?>
<?php endif; ?>