<?php
/**@var Eleanorsoft\Category\Block\Category $block*/

$current_category = $block->getCurrentCategory();
$id = $current_category->getData('entity_id');
$root_url = $current_category->getUrl();

$categories = $block->getCategories($id);
?>
<div class = "subcategory-container">
    <ul class = "subcategory-ul-container">
        <?php if ($categories->getSize()) {?>
            <li class = "subcategory-list-field">
                <a class="btn btn-subcategory-field" href="<?= $root_url?>"><?= htmlspecialchars(__('ALL'));?></a>
            </li>
        <?php } ?>
        <?php foreach ($categories as $category) { /** @var $category Magento\Catalog\Model\Category */?>
            <li class = "subcategory-list-field">
                <a class="btn btn-subcategory-field" href="<?= $category->getUrl()?>"><?= htmlspecialchars($category->getName());?></a>
            </li>
        <?php } ?>
    </ul>
</div>

