<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?php echo __('Your order # is: <span>%1</span>.', sprintf('<a href="%s" class="order-number">%s</a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
            <p><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>

    <?php echo $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>

    <?php echo $block->getChildHtml('checkout.registration'); ?>

    <?php if ($block->getOrderId()):?>
        <?php
            /** @var \Eleanorsoft\ShopOtherCategories\Block\Order\UpSellProduct $upSellProductsBlock */
            $upSellProductsBlock = $block->getChildBlock('up_sell.products');

            $upSellProductsBlock->loadOrderByIncrementId($block->getOrderId());

            echo $upSellProductsBlock->toHtml();
        ?>
    <?php endif;?>
    <?php
    /** @var \Eleanorsoft\AddThis\Block\Widget $addThisWidget */
    $addThisWidget = $block->getChildBlock('addthis.widget');

    echo $addThisWidget->getWidgetHtml();
    ?>
</div>