<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var \Magento\Wishlist\Block\Customer\Wishlist\Items $block */
$columns = $block->getColumns();
?>

<div class="products-grid wishlist container-product">
    <?php $iterator = 1; ?>
    <?php if (count($block->getItems())): ?>
        <?php
        foreach ($block->getItems() as $item):
            $iterator++;
            $product = $item->getProduct();
        ?>
            <div class="wish" id="item_<?= $this->escapeHtml($item->getId()); ?>">
                <?php foreach ($columns as $column): ?>
                    <?php $column->setItem($item); echo $column->toHtml($item);?>
                <?php endforeach; ?>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        <div class="message info empty">
            <span><?php /* @escapeNotVerified */ echo __('This Wish List has no Items');?></span>
        </div>
    <?php endif; ?>
</div>

<?php foreach ($columns as $column): ?>
    <?php echo $column->getAdditionalHtml();?>
<?php endforeach; ?>
