<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="apply-job-title">APPLY FOR THIS JOB</div>
<form class="form career"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
	<fieldset class="fieldset">
		<div class="field name required">
			<label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Full Name') ?></span></label>
			<div class="control">
				<input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
			</div>
		</div>
		<div class="field email required">
			<label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email Address') ?></span></label>
			<div class="control">
				<input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
			</div>
		</div>
		
		<div class="field telephone required">
			<label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Phone #') ?></span></label>
			<div class="control">
				<input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" data-validate="{required:true}" />
			</div>
		</div>
		
		<div class="field resume required">
			<label class="label" for="resume"><span><?php /* @escapeNotVerified */ echo __('Upload Resume') ?></span></label>
			<div class="control">
				<input name="resume" id="resume" title="<?php /* @escapeNotVerified */ echo __('Resume') ?>" class="input-file" type="file" data-validate="{required:true}" />
			</div>
		</div>
		<?php echo $block->getChildHtml('form.additional.info'); ?>
	</fieldset>
	<div class="actions-toolbar">
		<div class="primary">
			<input type="hidden" name="hideit" id="hideit" value="" />
			<button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
				<span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
			</button>
		</div>
	</div>
</form>

<?php if (false): ?>
	
	<table class="job-info">
		<tr>
			<th>Position Type:</th>
			<td>Stock Associate</td>
		</tr>
		<tr>
			<th>Part Time/Full Time:</th>
			<td>Part Time</td>
		</tr>
		<tr>
			<td colspan="2">
				<strong>Job Description:</strong>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut ligula auctor, cursus metus et, lobortis ante. Curabitur diam diam, dignissim non malesuada scelerisque, molestie at erat. Suspendisse dolor potenti. Maecenas sed lacinia arcu amet, consectetur adipiscing elit.</p>
			</td>
		</tr>
	</table>
	
<?php endif; ?>
