<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="field limiter">
    <div class="control">
        <div class="limiter-options">
            <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
	            <a data-role="limiter" href="javascript:;" data-value="<?php /* @escapeNotVerified */ echo $_key ?>"<?php if ($block->isLimitCurrent($_key)): ?> class="selected"<?php endif ?>>
		            <?php /* @escapeNotVerified */ echo $_limit ?>
	            </a>
            <?php endforeach; ?>
        </div>
    </div>
</div>
