<?php /** @var \Eleanorsoft\Subcategories\Block\SubcategoryList $block */ ?>
<?php $currentCategory = $block->getCurrentCategory(); ?>

<div class="categories-container">
    <a href="<?php echo $currentCategory->getUrl(); ?>">
        <div class="main-category category" style="background-color: <?php echo $block->getCategoryColor($currentCategory); ?>">
            <div class="category-name"><?php echo $currentCategory->getName(); ?></div>
            <div class="category-description"><?php echo $currentCategory->getDescription(); ?></div>
        </div>
    </a>
    <?php foreach ($block->getCurrentCategoryChildren() as $category): ?>
        <a href="<?php echo $category->getUrl(); ?>">
            <div class="<?php echo $category->getName(); ?>-category category" style="background-color: <?php echo $block->getCategoryColor($category); ?>">
                <div class="category-name"><?php echo $category->getName(); ?></div>
                <div class="category-image">
                    <img src="<?php echo $category->getImageUrl(); ?>" alt="<?php echo $category->getName(); ?>"/>
                </div>
            </div>
        </a>
    <?php endforeach; ?>
</div>