<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();
$product = $_item->getProduct();
$url = 'javascript:void(0);';
if ($product) {
    $url = $product->getUrlModel()->getUrl($product);
}

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$imageBuilder = $objectManager->create('Magento\Catalog\Block\Product\ImageBuilder');
$image = $imageBuilder->setProduct($product)
    ->setImageId('cart_page_product_thumbnail')
    ->create();

?>
<div class="container product-order" id="order-item-row-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">
    <div class="row justify-content-between">
        <div class="col-4" id="col-prod-photo">
            <a href="<?= $block->escapeHtml($url); ?>" class="pic-of-order-my-orders">
                <?= $image->toHtml(); ?>
            </a>
        </div>
        <div class="col-5 product-description-my-orders">
            <a href="<?= $block->escapeHtml($url); ?>"><?php echo $block->escapeHtml($_item->getName()) ?></a>
            <?php if ($_options = $block->getItemOptions()): ?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                        <?php if (!$block->getPrintStatus()): ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                                <?php else: ?>
                                    <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                                <?php endif; ?>
                            </dd>
                        <?php else: ?>
                            <dd>
                                <?php echo nl2br($block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value']))) ?>
                            </dd>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addtInfoBlock) :?>
                <?php echo $addtInfoBlock->setItem($_item)->toHtml(); ?>
            <?php endif; ?>
            <?php echo $block->escapeHtml($_item->getDescription()) ?>
        </div>
        <div class="col-2 order-price-my-orders">
            <?php echo $block->getItemRowTotalHtml(); ?>
        </div>
    </div>
</div>
<div class="w-100"></div>
<div class="line-between">
    <hr>
</div>