<?php /** @var  \Eleanorsoft\AjaxEntityLoader\Block\Test $block */ ?>
<div id="custom-component" data-bind="scope:'customcomponent'">
    <h1>Phtml</h1>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#custom-component": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "customcomponent": {
                        "component": "Eleanorsoft_AjaxEntityLoader/js/custom-component"
                    }
                }
            }
        }
    }
    </script>
</div>