<?php
/**
 * Override standard shipping calculator block.
 * Change title, pre-select USA
 */
?>
<?php if($this->_EnableModule()) : ?>
    <?php
    $country_code = "US"; $region_name = "";
    $region_code = ""; $region_id = ""; $zip_code = "";

    if($this->_getAutoIp()) :

        $address = $this->_getLocation();
        if(isset($address['country_code'])) {
            $country_code = strtoupper($address['country_code']);
        }

        if(isset($address['region_name'])) {
            $region_name = $address['region_name'];
        }

        if(isset($address['region_code'])) {
            $region_code = $address['region_code'];
        }

        if(isset($address['zip_code'])) {
            $zip_code = $address['zip_code'];
        }

        $region_id = $this->_getRegionId($region_code);

    endif;
    ?>

    <div class="estimaste-body">
        <div class="est-description">
            <p><strong><?php echo __("CALCULATE SHIPPING") ?></strong></p>
            <p><?php echo __("Enter destination to get a shipping cost.") ?></p>
        </div>

        <div id="shipping-input-form" class="detail-form-fields">
            <ul>
                <li class="item li_estimate_country_id">
                    <label class="label" for="country">
                        <span><?php echo __("Country") ?><span class="my-require">*</span></span>
                    </label>

                    <div class="control">
                        <select name="estimate[country_id]" id="estimate_country" class="js-country-placeholder-single" title="<?php echo __("Country") ?>">
                            <option value=""><?php echo __("Please select country") ?></option>
                            <?php
                            $countries = $block->getAvailableCountries();

                            foreach ($countries as $country) {
                                if(strtoupper($country->getCountryId()) == $country_code){
                                    $selected = "selected = 'selected'";
                                } else {
                                    $selected = "";
                                }
                                ?>
                                <option value="<?php echo $country->getCountryId(); ?>" <?php echo $selected; ?>><?php echo $country->getName(); ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </li>

                <li class="item li_estimate_region_id">
                    <label class="label" for="estimate_region_id">
                        <span><?php echo __("State/Province") ?><span class="my-require">*</span></span>
                    </label>

                    <div class="control">
                        <select id="estimate_region_id" name="estimate[region_id]" title="<?php echo __("State/Province") ?>" class="js-state-placeholder-single">
                            <option value=""><?php echo __("Please select State/Province") ?></option>
                        </select>

                        <input type="text" name="estimate[region]" id="input_region_id" value="<?php echo $region_name; ?>" class="input-text">
                    </div>
                </li>

                <!--
			<li class="item required">
				<label class="label" for="city">
					<span><?php //echo __("City") ?><span class="my-require">*</span></span>
				</label>

				<div class="control">
					<input type="text" name="estimate[city]" id="estimate_city" value="" title="<?php //echo __("City") ?>" class="input-text" data-validate="{required:true}" aria-required="true">
				</div>
			</li>
			-->

                <li class="item zip-code">
                    <label class="label" for="Zip/Postal Code">
                        <span><?php echo __("Zip/Postal Code") ?><span class="my-require">*</span></span>
                    </label>

                    <div class="control">
                        <input type="text" name="estimate[post_code]" id="estimate_postcode" value="<?php echo $zip_code; ?>" title="<?php echo __("Zip/Postal Code") ?>">
                    </div>
                </li>

                <?php if($this->_getAutoIp()) : ?>
                    <li class = "item">
                        <a href="javascript:void(0)" id="auto_ip"><?php echo __("Get informations from IP address."); ?></a>
                    </li>
                <?php endif; ?>

                <?php if($this->_getIncludeCart()): ?>
                    <li class = "item">
                        <input type="checkbox" id="include_cart" name="include_cart" value="1" checked><?php echo __("Include items in the cart."); ?>
                    </li>
                <?php endif; ?>

                <li class="item">
                    <div class="primary">
                        <button type="button" title="<?php echo $block->_getButtonTitle(); ?>" id="calculate-shipping" class="action submit primary btn-primary-estimate"><span><?php echo $block->_getButtonTitle(); ?></span></button>
                    </div>
                </li>
            </ul>
        </div>

        <!-- Shipping Rate -->
        <div class="est-description">
            <p><strong><?php echo __("Shipping Rates") ?></strong></p>
            <p><?php echo __("Please enter above informations and click calculate button to show estimate shipping results.") ?></p>
            <div id="shipping-result-form"></div>
        </div>
    </div>

    <script>
        require([
            'jquery',
            'select2'
        ], function($){
            var is_auto_ip = "<?php echo $this->_getAutoIp(); ?>";
            $(document).on('change','#estimate_country', function() {
                if(is_auto_ip) {
                    getRegion(this, true);
                } else {
                    getRegion(this, false);
                }
            });

            $(document).ready(function() {
                $("#input_region_id").val("");
                $("#input_region_id").css("display", "none");
                getRegion($('#estimate_country'), true);
                $('#estimate_country').trigger("change");
                $('.js-state-placeholder-single').attr('disabled','disabled');
            });

            $("#auto_ip").click(function() {
                $('#estimate_country').val('<?php echo $country_code; ?>').trigger('change');
                $('#estimate_region_id').val('<?php echo $region_id; ?>').trigger('change');
                $("#input_region_id").val("<?php echo $region_name; ?>");
                $("#estimate_postcode").val("<?php echo $zip_code; ?>");
                $("#input_region_id").val("<?php echo $region_name; ?>");
                $("#estimate_postcode").val("<?php echo $zip_code; ?>");
                $('#estshippingcost_content_option_product').animate({scrollTop: $("#shipping-input-form").offset().top}, 'slow');
            });

            $(".js-state-placeholder-single").select2({
                placeholder: "Select A State/Province",
                allowClear: true
            });

            $(".js-country-placeholder-single").select2({
                placeholder: "Select A Country",
                allowClear: true
            });

            function getRegion(element, isDocumentReady) {
                if( $('option:selected', element).index() ) {
                    var option = null;
                    var select = $('#estimate_region_id');

                    $('.js-state-placeholder-single').attr('disabled','disabled');
                    $('#input_region_id').attr('disabled','disabled');
                    $('#estimate_postcode').attr('disabled','disabled');

                    var select2_state = $('.li_estimate_region_id .select2');
                    var param = 'country='+$('#estimate_country').val();
                    $.ajax({
                        url: "<?php echo $this->getUrl('calculatorshipping/index/region') ?>",
                        data: param,
                        type: "POST",
                        dataType: 'json'
                    }).done(function (data) {
                        var region = data.value;
                        if(region.length > 0) {
                            $(".li_estimate_region_id .select2-selection.select2-selection--single").css("display", "block");
                            select.css("display", "block");
                            select2_state.css("display", "block");
                            $("#input_region_id").val("");
                            $("#input_region_id").css("display", "none");
                            $('option', select).remove();
                            option = new Option("<?php echo __("Please select State/Province") ?>", "");
                            select.append($(option));
                            $.each(region, function(text, key) {
                                option = new Option(key.name, key.region_id);
                                select.append($(option));
                            });

                            select.val('<?php echo $region_id; ?>').trigger('change');
                        } else {
                            if(isDocumentReady) {
                                $("#input_region_id").val("<?php echo $region_name; ?>");
                                $("#estimate_postcode").val("<?php echo $zip_code; ?>");
                            } else {
                                $("#input_region_id").val("");
                                $("#estimate_postcode").val("");
                            }
                            $(".li_estimate_region_id .select2-selection.select2-selection--single").css("display", "none");
                            $("#input_region_id").css("display", "block");
                            select.css("display", "none");
                            select2_state.css("display", "none");
                        }

                        $('.js-state-placeholder-single').removeAttr("disabled");
                        $('#input_region_id').removeAttr("disabled");
                        $('#estimate_postcode').removeAttr("disabled");
                    });
                }
            }
        });
    </script>

<?php endif; ?>