<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Create account form template
 *
 * @var \Magento\Customer\Block\Form\Register $block
 */
?>
<h3 class = "text-center new-customer-text">Please, use popup to <span data-toggle="modal" data-target="#SingInModal">login</span> or <span data-toggle="modal" data-target="#RegisterModal">register</span>...</h3>
<script type="text/javascript">
    requirejs(['jquery', 'domReady!'], function ($) {
        $('#register-modal').click();
    });
</script>