<?php /** @var \Eleanorsoft\ShopOtherCategories\Block\Order\UpSellProduct $block */ ?>
<?php if ($block->getOrder()): ?>
  <?php if ($block->getOrderUpSellProducts()->getSize()) : ?>

  <div class="block upsell">
    <div class="block-title title">
      <strong id="block-upsell-heading" role="heading" aria-level="2">
        <?php echo __('Shop Our Other Categories For Inspiration'); ?>
      </strong>
    </div>
    <div class="block-content content" aria-labelledby="block-upsell-heading">
      <div class="products wrapper grid products-grid products-upsell">
        <ol class="products list items product-items">

          <?php foreach ($block->getOrderUpSellProducts() as $product): ?>

          <li class="item product product-item">
            <div class="product-item-info">
              <a href="<?php echo $block->getProductUrl($product) ?>" class="product photo product-item-photo ui-link">
                <?php echo $block->getImage($product, 'upsell_products_list')->toHtml(); ?>
              </a>
              <div class="product details product-item-details">
                <strong class="product name product-item-name">
                  <a
                      class="product-item-link"
                      title="<?php echo $block->escapeHtml($product->getName()) ?>"
                      href="<?php echo $block->getProductUrl($product) ?>"
                  >
                    <?php echo $block->escapeHtml($product->getName()) ?>
                  </a>
                </strong>
                <?php echo $block->getProductPrice($product); ?>
              </div>
            </div>
          </li>

          <?php endforeach; ?>

        </ol>
      </div>
    </div>
  </div>

  <?php endif; ?>
<?php endif; ?>