<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getFrontendLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>

<?php if ($_attributeValue): ?>
	
	
	<div class="product attribute <?php /* @escapeNotVerified */ echo $_className?>">
	    <?php if ($_attributeLabel != 'none'): ?><a class="type" id="product-specs-toggle"><?php /* @escapeNotVerified */ echo $_attributeLabel?></a><?php endif; ?>
	    <div class="value" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute;?> id="product-specs-content"><?php /* @escapeNotVerified */ echo $_attributeValue; ?></div>
	</div>
	
	<script type="text/javascript">
		/* Simply invoke iffe of sidebarmodule */
		require(['jquery'], function ($) {
			$('#product-specs-toggle').click(function () {
				$(this).toggleClass('active');
				$('#product-specs-content').toggle();
			});
		});
	</script>
	
<?php endif; ?>