<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_product = $block->getProduct() ?>

<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="addthis_toolbox">
    <div class="custom_images">
        <a class="action share facebook" title="Share to Facebook"><span class="icon-facebook"></span></a>
        <a class="action share twitter" title="Share to Facebook"><span class="icon-twitter"></span></a>
        <a href="javascript:window.print()" class="action print"><span class="icon-print"></span></a>
        <?php if ($block->canEmailToFriend()): ?>
            <a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
               class="action mailto friend"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></a>
        <?php endif; ?>
    </div>
</div>
<?php
/** @var \Eleanorsoft\AddThis\Block\Widget $addThisWidget */
$addThisWidget = $block->getChildBlock('addthis.widget');
print $addThisWidget->getWidgetScript();
?>
