<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_InvisibleCaptcha
 */
?>
<?php
/**
 *
 * @see \Amasty\InvisibleCaptcha\Block\Captcha
 * @var \Amasty\InvisibleCaptcha\Block\Captcha $block
 */
?>
<?php if ($block->isModuleOn()) : ?>
    <script type="text/javascript">
        require(['jquery'], function ($) {
            window.formToProtectOnPage = [];
            formsToProtect = <?php echo $block->getCaptchaSelectorsJson() ?>;
            formsToProtect.forEach(function(item) {
                formToProtect = $(item)[0];
                if (formToProtect) {
                    window.formToProtectOnPage.push(formToProtect);
                }
            });

            if (window.formToProtectOnPage.length) {
                var recaptchaScript = document.createElement('script');
                recaptchaScript.src = 'https://www.google.com/recaptcha/api.js?onload=amInvisibleCaptchaOnloadCallback&render=explicit';
                recaptchaScript.attributes = 'async defer';
                document.body.appendChild(recaptchaScript);
            }

            window.amInvisibleCaptchaOnloadCallback = function () {
                for (var i = 0; i < window.formToProtectOnPage.length; i++) {
                    window.formToProtectOnPage[i].innerHTML +=
                        '<input type="hidden" name="amasty_invisible_token" value=""/>';
                }

                var id = "<?php echo $block->getData('id'); ?>";
                if (id) {
                    var additionalForm = document.getElementById(id).form;
                    if (additionalForm) {
                        window.formToProtectOnPage.push(additionalForm);
                    }
                }

                for (var i = 0; i < window.formToProtectOnPage.length; i++) {
                    var form = window.formToProtectOnPage[i];
                    if (form.tagName.toLowerCase() != 'form') {
                        continue;
                    }
                    id = form.querySelector("[type='submit']");

                    (function(form, id) {
                        grecaptcha.render(id, {
                            'sitekey': '<?php echo $block->getSiteKey(); ?>',
                            'callback': function(token) {
                                if ($(form).valid()){
                                    form.querySelector("[name='amasty_invisible_token']").setAttribute('value', token)
                                    form.submit();
                                } else {
                                    grecaptcha.reset();
                                }
                            }
                        });
                    })(form, id);
                }
            };
        });
    </script>
<?php endif; ?>
