<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Order\Items $block */
?>
<?php if($block->isPagerDisplayed()): ?>
    <?php echo $block->getPagerHtml() ?>
<?php endif ?>
<div class="container">
    <div class="row justify-content-between">
        <div class="col-3 product">
            <?= __('PRODUCT'); ?>
        </div>
        <div class="col-3 subtotal">
            <?= __('SUBTOTAL'); ?>
        </div>
    </div>
</div>
<div class="line-between">
    <hr>
</div>
<?php $items = $block->getItems(); ?>
<?php $giftMessage = ''?>
<?php foreach ($items as $item): ?>
    <?php if ($item->getParentItem()) continue; ?>
    <div class="container product-order">
        <div class="row justify-content-between">
            <?php echo $block->getItemHtml($item) ?>
            <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item', $item) && $item->getGiftMessageId()): ?>
                <?php $giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($item); ?>
                <a href="#"
                    id="order-item-gift-message-link-<?php /* @escapeNotVerified */ echo $item->getId() ?>"
                    class="action show"
                    aria-controls="order-item-gift-message-<?php /* @escapeNotVerified */ echo $item->getId() ?>"
                    data-item-id="<?php /* @escapeNotVerified */ echo $item->getId() ?>">
                    <?php /* @escapeNotVerified */ echo __('Gift Message') ?>
                </a>
                <?php $giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($item); ?>
                <div class="order-gift-message" id="order-item-gift-message-<?php /* @escapeNotVerified */ echo $item->getId() ?>" role="region" aria-expanded="false" tabindex="-1">
                    <a href="#"
                       title="<?php /* @escapeNotVerified */ echo __('Close') ?>"
                       aria-controls="order-item-gift-message-<?php /* @escapeNotVerified */ echo $item->getId()?>"
                       data-item-id="<?php /* @escapeNotVerified */ echo $item->getId()?>"
                       class="action close">
                        <?php /* @escapeNotVerified */ echo __('Close') ?>
                    </a>
                    <dl class="item-options">
                        <dt class="item-sender"><strong class="label"><?php /* @escapeNotVerified */ echo __('From') ?></strong><?php echo $block->escapeHtml($giftMessage->getSender()) ?></dt>
                        <dt class="item-recipient"><strong class="label"><?php /* @escapeNotVerified */ echo __('To') ?></strong><?php echo $block->escapeHtml($giftMessage->getRecipient()) ?></dt>
                        <dd class="item-message"><?php /* @escapeNotVerified */ echo $this->helper('Magento\GiftMessage\Helper\Message')->getEscapedGiftMessage($item) ?></dd>
                    </dl>
                </div>
            <?php endif ?>
        </div>
    </div>
<?php endforeach; ?>
<?php if($block->isPagerDisplayed()): ?>
    <?php echo $block->getPagerHtml();?>
<?php endif ?>
<?php echo $block->getChildHtml('order_totals') ?>
<?php if ($giftMessage): ?>
    <script type="text/x-magento-init">
    {
        "a.action.show, a.action.close": {
            "giftMessage": {}
        }
    }
</script>
<?php endif; ?>
