<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<div class="container all-about-price">
    <div class="row price-components">
        <?php foreach ($block->getTotals() as $_code => $_total): ?>
            <?php if ($_total->getBlockName()): ?>
                <?php echo $block->getChildHtml($_total->getBlockName(), false); ?>
            <?php else:?>
                <?php if ($_total->getStrong()):?>
    </div>
    <div class="row total-price">
                <?php endif; ?>
                <div class="<?php if ($_total->getStrong()) { ?>col-md-3 col-5<?php } else { ?>col-md-3 col-5<?php } ?> offset-md-6 <?php /* @escapeNotVerified */ echo $_code?>">
                    <?php if ($_total->getStrong()) { ?>
                        <?= __('Total'); ?>
                    <?php } else { ?>
                        <?php echo $block->escapeHtml($_total->getLabel());?>
                    <?php } ?>
                </div>
                <div class="<?php if ($_total->getStrong()) { ?>col-md-3 col-5 all-price<?php } else { ?>col-md-3 col-5 components<?php } ?> <?php /* @escapeNotVerified */ echo $_code?>">
                    <?php /* @escapeNotVerified */ echo $block->formatValue($_total) ?>
                </div>
            <?php endif?>
        <?php endforeach?>
    </div>
</div>
<div class="line-between">
    <hr>
</div>