<div class="contact">
    <div class="row">
        <div class="col-xs-12 col-sm-6 hidden-xs">
            <div class="contact-title">
                <h3>PLEASE DO GET IN TOUCH!</h3>
            </div>
            <div class="contact-address-block">
                <div class="contact-address">
                    <div class="media">
                        <div class="media-body">
                            Please feel free to contact us by email, regular mail, or phone.
                        </div>
                    </div>
                </div>
                <div class="contact-contactinfo">
                    <div class="media">
                        <div class="media-body contact-telephone">
                            Address: 8th Meraguza St.(the Flea Market) Tel Aviv - Jaffa
                        </div>
                    </div>
                    <div class="media">
                        <div class="media-body contact-mobile">
                            <p class="s-phone">Phone: 00972.3.6041405</p>
                        </div>
                    </div>
                    <div class="media">
                        <div class="media-body contact-emailto">
                            <p><a href="mailto:stores@company.com">Email: shop@asufadesign.com</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6" id="wholesale-form-container" data-bind="scope: 'customProject'">
            <h3>Write Us</h3>
            <div class="page messages" style="display: none;">
                <div>
                    <div class="messages">
                        <div class="message">
                            <div></div>
                        </div>
                    </div>
                </div>
            </div>
            <form class="contact-form"
                    action="<?php /* @escapeNotVerified */ print $block->getFormAction(); ?>"
                    id="form-artist"
                    data-bind="submit: submitForm"
                    method="post"
                    data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
                    data-mage-init='{"validation":{}}'>
                <p>Please feel free to contact us by email, regular mail, phone or instant message</p>
                <p><input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Your Name') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Your Name') ?>" class="input-text" type="text" data-validate="{required:true}"/></p>
                <p><input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Your Email Address') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Your Email Address') ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/></p>
                <p><input name="subject" id="subject" title="<?php /* @escapeNotVerified */ echo __('Message Subject') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Message Subject') ?>" class="input-text" type="text" data-validate="{required:true}"/></p
                <p><input name="phone" id="phone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="input-text" type="text" data-validate="{required:true}"/></p
                <p><input name="photo[]" multiple id="photo" title="<?php /* @escapeNotVerified */ echo __('Upload Sample Photos') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Upload Sample Photos') ?>" class="input-text" type="file" /></p>
                <p><textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('Comments') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Comments') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea></p>
                <div class="form-actions">
                    <input type="hidden" name="hideit" id="hideit" value="" />
                    <button type="submit" title="<?php /* @escapeNotVerified */ echo __('send message') ?>" class="btn-novetty btn-raised primary">
                         <span><?php /* @escapeNotVerified */ echo __('send message') ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "customProject": {
                    "component": "Eleanorsoft_CustomForm/js/custom"
                }
            }
        }
    }
}
</script>