<?php
/**@var Eleanorsoft\Category\Block\Category $block*/
$categories = $block->getCategories();

?>
<div>
    <ul>
<?php foreach ($categories as $category) { /** @var $category Magento\Catalog\Model\Category */?>
   <li>
       <a href="<?= $category->getUrl()?>">
           <img src="<?= $block->escapeHtml($category->getImageUrl());?>" alt="<?= $block->escapeHtml($category->getName());?>">
       </a>
   </li>
<?php } ?>
    </ul>
</div>

