<?php
/**@var Eleanorsoft\Category\Block\Category $block*/

$id = $block->getCurrentCategoryId();
$categories = $block->getCategories($id);

?>
<div>
    <ul>
<?php foreach ($categories as $category) { /** @var $category Magento\Catalog\Model\Category */?>
   <li>
       <a href="<?= $category->getUrl()?>">
           <img src="<?= htmlspecialchars($category->getImageUrl());?>" alt="<?= htmlspecialchars($category->getName());?>">
       </a>
   </li>
<?php } ?>
    </ul>
</div>

