<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Eleanorsoft\LayeredNavigation\Block\SwatchesRenderLayered */
?>
<?php $swatchData = $block->getSwatchData(); ?>
<ol class="items filter-container swatch-attribute-options clearfix" data-filter-code="<?php echo $swatchData['attribute_code']; ?>">
    <?php foreach ($swatchData['options'] as $option => $label): ?>
        <li class="item">
            <?php if (isset($swatchData['swatches'][$option]['type'])) { ?>
                <?php switch ($swatchData['swatches'][$option]['type']) {
                    case '3':
                        ?>
                        <div class="swatch-option <?php /* @escapeNotVerified */ echo $label['custom_style'] ?>"
                             option-type="3"
                             option-id="<?php /* @escapeNotVerified */ echo $option ?>"
                             option-label="<?php /* @escapeNotVerified */ echo $label['label'] ?>"
                             option-tooltip-thumb=""
                             option-tooltip-value=""
                            ></div>
                        <?php    break;
                    case '2':
                        ?>
                        <?php $swatchThumbPath = $block->getSwatchPath('swatch_thumb',
                        $swatchData['swatches'][$option]['value']); ?>
                        <?php $swatchImagePath = $block->getSwatchPath('swatch_image',
                        $swatchData['swatches'][$option]['value']); ?>
                        <div class="swatch-option image <?php /* @escapeNotVerified */ echo $label['custom_style'] ?>"
                             option-type="2"
                             option-id="<?php /* @escapeNotVerified */ echo $option ?>"
                             option-label="<?php /* @escapeNotVerified */ echo $label['label'] ?>"
                             option-tooltip-thumb="<?php /* @escapeNotVerified */ echo $swatchThumbPath ?>"
                             option-tooltip-value=""
                             style="background: url(<?php /* @escapeNotVerified */ echo $swatchImagePath ?>) no-repeat center; background-size: initial;"></div>
                        <?php    break;
                    case '1':
                        ?>
                        <?php $color = $swatchData['swatches'][$option]['value']; ?>
                        <label id="filter-label-<?php /* @escapeNotVerified */ echo $label['label'] ?>" class="control control--checkbox">
                            <div class="swatch-option color <?php echo $label['custom_style'] ?>"
                                 style="background: <?php /* @escapeNotVerified */ echo $color ?> no-repeat center; background-size: initial;"></div>
                            <input
                                <?php echo $block->isFilterValueActive($swatchData['attribute_code'], $option) ? 'checked' : null; ?>
                                type="checkbox"
                                id="filter-label-<?php /* @escapeNotVerified */ echo $option; ?>"
                                data-filter-value="<?php echo $option; ?>"
                            />
                            <?php /* @escapeNotVerified */ echo $label['label'] ?>
                            <span class="control__indicator"></span>
                        </label>

                        <?php    break;
                    case '0':
                    default:
                        ?>
                            <div class="swatch-option text <?php /* @escapeNotVerified */ echo $label['custom_style'] ?>"
                                 option-type="0"
                                 option-id="<?php /* @escapeNotVerified */ echo $option ?>"
                                 option-label="<?php /* @escapeNotVerified */ echo $label['label'] ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value=""
                                ><?php /* @escapeNotVerified */ echo $swatchData['swatches'][$option]['value'] ?></div>
                        <?php    break;
                } ?>
            <?php } ?>
        </li>
    <?php endforeach; ?>
</ol>